<?php

namespace Database\Seeders;

use App\Models\AiFeaturePricing;
use Illuminate\Database\Seeder;

/**
 * AI Feature Pricing Seeder
 *
 * Popola tabella ai_feature_pricing con tutti i prezzi da TOKENOMICS_EGILI_EQUILIBRIUM.md
 *
 * @package FlorenceEGI\Seeders
 * @author Padmin D. Curtis (AI Partner OS3.0)
 * @version 1.0.0
 * @date 2025-10-22
 * @source docs/ai/TOKENOMICS_EGILI_EQUILIBRIUM.md lines 454-570
 */
class AiFeaturePricingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $features = [
            // === AI SERVICES ===
            [
                'feature_code' => 'ai_quick_check',
                'feature_name' => 'Quick Check (metadata only)',
                'feature_description' => 'Analisi rapida basata solo su metadata EGI, senza AI Vision',
                'feature_category' => 'ai_services',
                'cost_fiat_eur' => null,
                'cost_egili' => null,
                'is_free' => true,
                'free_monthly_limit' => 3,
                'min_tier_required' => 'free',
                'display_order' => 10,
                'is_featured' => true,
                'icon_name' => 'superadmin-ai-brain',
                'badge_color' => 'green',
                'benefits' => ['Analisi metadata', 'Suggerimenti base', 'Illimitato'],
            ],
            [
                'feature_code' => 'ai_egi_deep_analysis',
                'feature_name' => 'EGI Deep Analysis (full AI Vision)',
                'feature_description' => 'Analisi completa con AI Vision per singolo EGI',
                'feature_category' => 'ai_services',
                'cost_fiat_eur' => 4.90,
                'cost_egili' => 50,
                'min_tier_required' => 'free',
                'display_order' => 20,
                'is_featured' => true,
                'icon_name' => 'superadmin-ai-brain',
                'badge_color' => 'blue',
                'benefits' => ['Image analysis AI', 'Pricing suggestions', '3 action items marketing'],
            ],
            [
                'feature_code' => 'ai_3_egi_bundle',
                'feature_name' => '3 EGI Bundle',
                'feature_description' => 'Bundle analisi AI per 3 EGI con 10% sconto',
                'feature_category' => 'ai_services',
                'cost_fiat_eur' => 9.90,
                'cost_egili' => 90,
                'is_bundle' => true,
                'bundle_type' => '3_egi',
                'discount_percentage' => 10,
                'bundle_features' => ['ai_egi_deep_analysis', 'ai_egi_deep_analysis', 'ai_egi_deep_analysis'],
                'min_tier_required' => 'free',
                'display_order' => 30,
                'icon_name' => 'superadmin-ai-brain',
                'badge_color' => 'purple',
                'benefits' => ['3x analisi complete', '10% sconto', 'Image analysis AI', 'Pricing suggestions', 'Action items marketing'],
            ],
            [
                'feature_code' => 'ai_collection_sample',
                'feature_name' => 'Collection Smart Sample (12 EGI)',
                'feature_description' => 'Analisi smart di 12 EGI per strategia collection completa',
                'feature_category' => 'ai_services',
                'cost_fiat_eur' => 9.90,
                'cost_egili' => 95,
                'is_bundle' => true,
                'bundle_type' => 'collection_sample',
                'min_tier_required' => 'free',
                'display_order' => 40,
                'icon_name' => 'superadmin-ai-brain',
                'badge_color' => 'gold',
                'benefits' => ['12 EGI analysis', 'Collection strategy', 'Top/bottom performers', 'Pricing optimization'],
                'feature_parameters' => ['num_egis' => 12, 'includes_strategy' => true],
            ],
            [
                'feature_code' => 'ai_monthly_monitoring',
                'feature_name' => 'Monthly AI Monitoring (PRO)',
                'feature_description' => 'Monitoraggio AI mensile con report settimanali',
                'feature_category' => 'ai_services',
                'cost_fiat_eur' => 19.00,
                'cost_egili' => 180,
                'is_recurring' => true,
                'recurrence_period' => 'monthly',
                'min_tier_required' => 'pro',
                'display_order' => 50,
                'icon_name' => 'superadmin-ai-statistics',
                'badge_color' => 'premium',
                'benefits' => ['Weekly reports', 'AI alerts', 'Trends analysis', 'Priority support'],
            ],

            // === PREMIUM VISIBILITY ===
            [
                'feature_code' => 'featured_homepage_24h',
                'feature_name' => 'Homepage Spotlight (24h)',
                'feature_description' => 'EGI in evidenza homepage per 24 ore',
                'feature_category' => 'premium_visibility',
                'cost_egili' => 200,
                'duration_hours' => 24,
                'expires' => true,
                'min_tier_required' => 'free',
                'display_order' => 100,
                'icon_name' => 'superadmin-egili-token',
                'expected_roi_multiplier' => 3.00,
                'benefits' => ['Homepage spotlight', '+300% views avg', '24h duration'],
            ],
            [
                'feature_code' => 'featured_category_7d',
                'feature_name' => 'Category Featured (7 giorni)',
                'feature_description' => 'EGI in evidenza nella categoria per 7 giorni',
                'feature_category' => 'premium_visibility',
                'cost_egili' => 500,
                'duration_hours' => 168,
                'expires' => true,
                'min_tier_required' => 'free',
                'display_order' => 110,
                'expected_roi_multiplier' => 3.00,
            ],
            [
                'feature_code' => 'newsletter_inclusion',
                'feature_name' => 'Newsletter Inclusion',
                'feature_description' => 'Inclusione EGI nella newsletter piattaforma',
                'feature_category' => 'premium_visibility',
                'cost_egili' => 300,
                'min_tier_required' => 'free',
                'display_order' => 120,
                'benefits' => ['500+ guaranteed views', 'Newsletter feature', 'Direct to collectors'],
            ],
            [
                'feature_code' => 'social_media_feature',
                'feature_name' => 'Social Media Feature',
                'feature_description' => 'Feature su canali social ufficiali',
                'feature_category' => 'premium_visibility',
                'cost_egili' => 150,
                'min_tier_required' => 'free',
                'display_order' => 130,
            ],
            [
                'feature_code' => 'boost_24h',
                'feature_name' => '24h Boost (+50% views)',
                'feature_description' => 'Boost visibilità 24 ore con +50% views',
                'feature_category' => 'premium_visibility',
                'cost_egili' => 100,
                'duration_hours' => 24,
                'expires' => true,
                'min_tier_required' => 'free',
                'display_order' => 140,
                'expected_roi_multiplier' => 1.50,
            ],
            [
                'feature_code' => 'boost_7d',
                'feature_name' => '7 giorni Boost (sconto -30%)',
                'feature_description' => 'Boost visibilità 7 giorni con sconto',
                'feature_category' => 'premium_visibility',
                'cost_egili' => 500,
                'duration_hours' => 168,
                'expires' => true,
                'discount_percentage' => 30,
                'min_tier_required' => 'free',
                'display_order' => 150,
                'expected_roi_multiplier' => 1.50,
            ],
            [
                'feature_code' => 'boost_30d',
                'feature_name' => '30 giorni Boost (sconto -50%)',
                'feature_description' => 'Boost visibilità 30 giorni con sconto maggiorato',
                'feature_category' => 'premium_visibility',
                'cost_egili' => 1500,
                'duration_hours' => 720,
                'expires' => true,
                'discount_percentage' => 50,
                'min_tier_required' => 'free',
                'display_order' => 160,
                'expected_roi_multiplier' => 2.00,
            ],
            [
                'feature_code' => 'boost_permanent_pro',
                'feature_name' => 'Permanent Boost Slot (PRO)',
                'feature_description' => 'Slot boost permanente per tier PRO',
                'feature_category' => 'premium_visibility',
                'cost_egili' => 5000,
                'expires' => false,
                'min_tier_required' => 'pro',
                'display_order' => 170,
                'expected_roi_multiplier' => 2.50,
            ],

            // === PREMIUM PROFILE ===
            [
                'feature_code' => 'custom_badge',
                'feature_name' => 'Custom Badge Design',
                'feature_description' => 'Badge personalizzato per profilo',
                'feature_category' => 'premium_profile',
                'cost_egili' => 200,
                'min_tier_required' => 'free',
                'display_order' => 200,
            ],
            [
                'feature_code' => 'verified_checkmark',
                'feature_name' => 'Verified Checkmark',
                'feature_description' => 'Checkmark verificato (manuale review required)',
                'feature_category' => 'premium_profile',
                'cost_egili' => 500,
                'requires_approval' => true,
                'min_tier_required' => 'free',
                'display_order' => 210,
            ],
            [
                'feature_code' => 'profile_theme',
                'feature_name' => 'Profile Theme/Skin',
                'feature_description' => 'Tema personalizzato profilo',
                'feature_category' => 'premium_profile',
                'cost_egili' => 100,
                'min_tier_required' => 'free',
                'display_order' => 220,
            ],
            [
                'feature_code' => 'banner_custom',
                'feature_name' => 'Banner Space Custom',
                'feature_description' => 'Spazio banner personalizzato',
                'feature_category' => 'premium_profile',
                'cost_egili' => 300,
                'min_tier_required' => 'free',
                'display_order' => 230,
            ],
            [
                'feature_code' => 'custom_url_slug',
                'feature_name' => 'Custom URL Slug',
                'feature_description' => 'URL personalizzato profilo',
                'feature_category' => 'premium_profile',
                'cost_egili' => 150,
                'min_tier_required' => 'free',
                'display_order' => 240,
            ],
            [
                'feature_code' => 'remove_ads_30d',
                'feature_name' => 'Remove Ads (30gg)',
                'feature_description' => 'Rimozione ads per 30 giorni',
                'feature_category' => 'premium_profile',
                'cost_egili' => 200,
                'duration_hours' => 720,
                'expires' => true,
                'min_tier_required' => 'free',
                'display_order' => 250,
            ],
            [
                'feature_code' => 'animated_avatar',
                'feature_name' => 'Animated Avatar',
                'feature_description' => 'Avatar animato profilo',
                'feature_category' => 'premium_profile',
                'cost_egili' => 250,
                'min_tier_required' => 'free',
                'display_order' => 260,
            ],

            // === PREMIUM ANALYTICS ===
            [
                'feature_code' => 'analytics_dashboard_pro',
                'feature_name' => 'Analytics Dashboard PRO',
                'feature_description' => 'Dashboard analytics avanzata mensile',
                'feature_category' => 'premium_analytics',
                'cost_egili' => 500,
                'is_recurring' => true,
                'recurrence_period' => 'monthly',
                'min_tier_required' => 'starter',
                'display_order' => 300,
            ],
            [
                'feature_code' => 'export_data_csv',
                'feature_name' => 'Export Data CSV',
                'feature_description' => 'Export dati in formato CSV',
                'feature_category' => 'premium_analytics',
                'cost_egili' => 50,
                'min_tier_required' => 'free',
                'display_order' => 310,
            ],
            [
                'feature_code' => 'competitor_tracking',
                'feature_name' => 'Competitor Tracking (5 artists)',
                'feature_description' => 'Tracking competitori mensile (max 5)',
                'feature_category' => 'premium_analytics',
                'cost_egili' => 300,
                'is_recurring' => true,
                'recurrence_period' => 'monthly',
                'min_tier_required' => 'pro',
                'display_order' => 320,
                'feature_parameters' => ['max_competitors' => 5],
            ],
            [
                'feature_code' => 'price_history_detailed',
                'feature_name' => 'Price History Detailed',
                'feature_description' => 'Storico prezzi dettagliato',
                'feature_category' => 'premium_analytics',
                'cost_egili' => 100,
                'min_tier_required' => 'free',
                'display_order' => 330,
            ],
            [
                'feature_code' => 'bulk_operations',
                'feature_name' => 'Bulk Operations (traits/metadata)',
                'feature_description' => 'Operazioni bulk su traits e metadata',
                'feature_category' => 'premium_analytics',
                'cost_egili' => 150,
                'min_tier_required' => 'starter',
                'display_order' => 340,
            ],
            [
                'feature_code' => 'api_access_developer',
                'feature_name' => 'API Access (developer)',
                'feature_description' => 'Accesso API developer mensile',
                'feature_category' => 'premium_analytics',
                'cost_egili' => 1000,
                'is_recurring' => true,
                'recurrence_period' => 'monthly',
                'min_tier_required' => 'business',
                'display_order' => 350,
            ],

            // === EXCLUSIVE ACCESS ===
            [
                'feature_code' => 'early_access_drop_24h',
                'feature_name' => 'Early Access Drop (24h advance)',
                'feature_description' => 'Accesso anticipato drop 24h prima',
                'feature_category' => 'exclusive_access',
                'cost_egili' => 150,
                'min_tier_required' => 'free',
                'display_order' => 400,
            ],
            [
                'feature_code' => 'private_sale_access',
                'feature_name' => 'Private Sale Access',
                'feature_description' => 'Accesso vendite private',
                'feature_category' => 'exclusive_access',
                'cost_egili' => 300,
                'min_tier_required' => 'starter',
                'display_order' => 410,
            ],
            [
                'feature_code' => 'vip_livestream_ticket',
                'feature_name' => 'VIP Livestream Ticket',
                'feature_description' => 'Ticket VIP per livestream',
                'feature_category' => 'exclusive_access',
                'cost_egili' => 50,
                'min_tier_required' => 'free',
                'display_order' => 420,
            ],
            [
                'feature_code' => 'masterclass_access',
                'feature_name' => 'Masterclass Access',
                'feature_description' => 'Accesso masterclass piattaforma',
                'feature_category' => 'exclusive_access',
                'cost_egili' => 200,
                'min_tier_required' => 'free',
                'display_order' => 430,
            ],
            [
                'feature_code' => 'artist_meet_greet',
                'feature_name' => 'Artist Meet & Greet',
                'feature_description' => 'Incontro con artista',
                'feature_category' => 'exclusive_access',
                'cost_egili' => 500,
                'min_tier_required' => 'starter',
                'display_order' => 440,
            ],
            [
                'feature_code' => 'exclusive_discord_30d',
                'feature_name' => 'Exclusive Discord Channel (30gg)',
                'feature_description' => 'Accesso canale Discord esclusivo 30 giorni',
                'feature_category' => 'exclusive_access',
                'cost_egili' => 200,
                'duration_hours' => 720,
                'expires' => true,
                'min_tier_required' => 'free',
                'display_order' => 450,
            ],
        ];

        foreach ($features as $feature) {
            AiFeaturePricing::updateOrCreate(
                ['feature_code' => $feature['feature_code']],
                $feature
            );
        }

        $this->command->info('✅ AI Feature Pricing seeded successfully (' . count($features) . ' features)');
    }
}