#!/usr/bin/env python3
"""
Script per creare i file di traduzione dei traits mantenendo la struttura esatta del file italiano
"""

# Dizionari di traduzione per ogni lingua
translations = {
    'en': {
        # Categories
        'Materiali': 'Materials',
        'Visuale': 'Visual', 
        'Dimensioni': 'Dimensions',
        'Speciale': 'Special',
        'Sostenibilità': 'Sustainability',
        'Culturale': 'Cultural',
        'Accessori': 'Accessories',
        'Categorie': 'Categories',
        
        # Trait Types
        'Materiale Primario': 'Primary Material',
        'Finitura': 'Finish',
        'Tecnica': 'Technique',
        'Colore Primario': 'Primary Color',
        'Stile': 'Style',
        'Atmosfera': 'Mood',
        'Dimensione': 'Size',
        'Peso': 'Weight',
        'Altezza': 'Height',
        'Larghezza': 'Width',
        'Edizione': 'Edition',
        'Firma': 'Signature',
        'Condizione': 'Condition',
        'Anno di Creazione': 'Year Created',
        'Contenuto Riciclato': 'Recycled Content',
        'Impronta Carbonica': 'Carbon Footprint',
        'Certificazione Eco': 'Eco Certification',
        'Punteggio Sostenibilità': 'Sustainability Score',
        'Origine Culturale': 'Cultural Origin',
        'Focus Tematico': 'Thematic Focus',
        'Tecnica Artigianale': 'Artisan Technique',
        'Tipo di Edizione': 'Edition Type',
        
        # Accessory Types
        'Tipo di Accessorio': 'Accessory Type',
        'Componente Accessorio': 'Accessory Component',
        'Tipo di Chiusura': 'Closure Type',
        'Finitura Hardware': 'Hardware Finish',
        'Tipo di Cinghia': 'Strap Type',
        'Layout Tasche': 'Pocket Layout',
        'Categoria Dimensioni': 'Size Category',
        'Texture': 'Texture',
        'Fodera': 'Lining',
        'Occasione': 'Occasion',
        'Compatibilità': 'Compatibility',
        'Protezione Acqua': 'Water Protection',
        'Personalizzazione': 'Personalization',
        'Struttura': 'Structure',
        
        # Values - Categories
        'Giochi': 'Games',
        'Business': 'Business',
        'Arte': 'Art',
        'Musica': 'Music',
        'Sport': 'Sports',
        'Educazione': 'Education',
        'Scienza': 'Science',
        'Tecnologia': 'Technology',
        'Collezionabili': 'Collectibles',
        'Fantasy': 'Fantasy',
        'Storia': 'History',
        'Natura': 'Nature',
        'Moda': 'Fashion',
        'Cibo': 'Food',
        'Viaggi': 'Travel',
        
        # Materials
        'Legno': 'Wood',
        'Metallo': 'Metal',
        'Tela': 'Canvas',
        'Carta': 'Paper',
        'Ceramica': 'Ceramic',
        'Vetro': 'Glass',
        'Pietra': 'Stone',
        'Tessuto': 'Fabric',
        'Plastica': 'Plastic',
        'Tecnica Mista': 'Mixed Media',
        'Pelle': 'Leather',
        'Argilla': 'Clay',
        'Marmo': 'Marble',
        'Granito': 'Granite',
        'Cemento': 'Concrete',
        'Gesso': 'Plaster',
        'Resina': 'Resin',
        'Gomma': 'Rubber',
        'Acrilico': 'Acrylic',
        'Inchiostro': 'Ink',
        'Pittura a Olio': 'Oil Paint',
        'Acquerello': 'Watercolor',
        'Carboncino': 'Charcoal',
        'Pastello': 'Pastel',
        'Digitale': 'Digital',
        'Fotografico': 'Photographic',
        'Organico': 'Organic',
        'Riciclato': 'Recycled',
        'Composito': 'Composite',
        
        # Finish
        'Opaco': 'Matte',
        'Lucido': 'Glossy',
        'Satinato': 'Satin',
        'Grezzo': 'Raw',
        'Lucidato': 'Polished',
        'Spazzolato': 'Brushed',
        'Patina': 'Patina',
        'Texturizzato': 'Textured',
        
        # Primary Colors
        'Rosso': 'Red',
        'Blu': 'Blue',
        'Verde': 'Green',
        'Giallo': 'Yellow',
        'Arancione': 'Orange',
        'Viola': 'Purple',
        'Nero': 'Black',
        'Bianco': 'White',
        'Grigio': 'Gray',
        'Marrone': 'Brown',
        'Oro': 'Gold',
        'Argento': 'Silver',
        
        # Style
        'Moderno': 'Modern',
        'Classico': 'Classic',
        'Minimalista': 'Minimalist',
        'Astratto': 'Abstract',
        'Realistico': 'Realistic',
        'Surreale': 'Surreal',
        'Pop Art': 'Pop Art',
        'Rinascimentale': 'Renaissance',
        'Contemporaneo': 'Contemporary',
        
        # Mood
        'Sereno': 'Serene',
        'Energico': 'Energetic',
        'Misterioso': 'Mysterious',
        'Gioioso': 'Joyful',
        'Melanconico': 'Melancholic',
        'Drammatico': 'Dramatic',
        'Pacifico': 'Peaceful',
        'Intenso': 'Intense',
        
        # Size
        'Extra Piccolo': 'Extra Small',
        'Piccolo': 'Small',
        'Medio': 'Medium',
        'Grande': 'Large',
        'Extra Grande': 'Extra Large',
        
        # Edition
        '1/1': '1/1',
        'Edizione Limitata': 'Limited Edition',
        'Edizione Aperta': 'Open Edition',
        'Prova d\'Artista': 'Artist Proof',
        'Prima Edizione': 'First Edition',
        
        # Signature
        'Firmato': 'Signed',
        'Non Firmato': 'Unsigned',
        'Firmato e Numerato': 'Signed & Numbered',
        'Certificato di Autenticità': 'Certificate of Authenticity',
        
        # Condition
        'Perfetto': 'Mint',
        'Eccellente': 'Excellent',
        'Buono': 'Good',
        'Discreto': 'Fair',
        'Restaurato': 'Restored',
        'Vintage': 'Vintage',
        'Nuovo': 'New',
        
        # Carbon Footprint
        'Neutro in Carbonio': 'Carbon Neutral',
        'Basso Impatto': 'Low Impact',
        'Medio Impatto': 'Medium Impact',
        'Compensato': 'Offset Compensated',
        
        # Eco Certification
        'Certificato FSC': 'FSC Certified',
        'Biologico': 'Organic',
        'Commercio Equo': 'Fair Trade',
        'Biodegradabile': 'Biodegradable',
        'Nessuna': 'None',
        
        # Accessory Type
        'Borsa': 'Bag',
        'Zaino': 'Backpack',
        'Borsa Tote': 'Tote',
        'Tracolla': 'Crossbody',
        'Borsa a Spalla': 'Shoulder Bag',
        'Pochette': 'Clutch',
        'Portafoglio': 'Wallet',
        'Porta Carte': 'Card Holder',
        'Portamonete': 'Coin Purse',
        'Cintura': 'Belt',
        'Portachiavi': 'Keychain',
        'Custodia Telefono': 'Phone Case',
        'Custodia Laptop': 'Laptop Sleeve',
        'Cinturino Orologio': 'Watch Strap',
        'Occhiali da Sole': 'Sunglasses',
        'Montatura Occhiali': 'Glasses Frame',
        'Cappello': 'Hat',
        'Sciarpa': 'Scarf',
        'Guanti': 'Gloves',
        'Ombrello': 'Umbrella',
        
        # Hardware
        'Fibbia': 'Buckle',
        'Cerniera': 'Zipper',
        'Chiusura Magnetica': 'Magnetic Snap',
        'Fermaglio': 'Clasp',
        'Chiusura a Torsione': 'Twist Lock',
        'Lucchetto': 'Padlock',
        'Gancio': 'Hook',
        'Laccio': 'Tie',
        'Velcro': 'Velcro',
        'Bottone': 'Button',
        'Borchia': 'Stud',
        'Rivetto': 'Rivet',
        'Catena': 'Chain',
        
        # Structure and other
        'Morbido': 'Soft',
        'Semi-Strutturato': 'Semi-Structured',
        'Strutturato': 'Structured',
        'Imbottito': 'Padded',
        'Liscio': 'Smooth',
        'Goffrato': 'Pebbled',
        'Saffiano': 'Saffiano',
        'Trapuntato': 'Quilted',
        'Intrecciato': 'Woven',
        'Impresso': 'Embossed',
        'Effetto Coccodrillo': 'Croc-Embossed',
        'Finitura Scamosciata': 'Suede Finish',
        'Matelassé': 'Matelassé',
        'Senza Fodera': 'Unlined',
        'Fodera in Cotone': 'Cotton Lining',
        'Fodera in Microfibra': 'Microfiber Lining',
        'Fodera Scamosciata': 'Suede Lining',
        'Fodera in Raso': 'Satin Lining',
        'Quotidiano': 'Everyday',
        'Viaggio': 'Travel',
        'Sera': 'Evening',
        'Formale': 'Formal',
        'Outdoor': 'Outdoor',
        'Telefono': 'Phone',
        'Tablet': 'Tablet',
        'Laptop 13"': 'Laptop 13"',
        'Laptop 14"': 'Laptop 14"',
        'Laptop 15"': 'Laptop 15"',
        'Laptop 16"': 'Laptop 16"',
        'Passaporto': 'Passport',
        'Resistente agli Schizzi': 'Splash Resistant',
        'Resistente all\'Acqua': 'Water Resistant',
        'Impermeabile': 'Waterproof',
        'Monogramma': 'Monogram',
        'Incisione': 'Engraving',
        'Patch Personalizzata': 'Custom Patch',
        'Colore Personalizzato': 'Custom Color',
        
        # Additional
        'Regolabile': 'Adjustable',
        'Rimovibile': 'Detachable',
        'Manico Superiore': 'Top Handle',
        'Spallacci Zaino': 'Backpack Straps',
        'Cinturino da Polso': 'Wristlet',
        'Mini': 'Mini',
        'Oversize': 'Oversized',
        'Coulisse': 'Drawstring',
        'Gancio e Occhiello': 'Hook-and-Loop',
        'Tasto a Leva': 'Toggle',
        'Clip': 'Clip',
        'Aperto in Alto': 'Open Top',
        'Oro Rosa': 'Rose Gold',
        'Nichel': 'Nickel',
        'Gunmetal': 'Gunmetal',
        'Ottone': 'Brass',
        'Antico': 'Antique',
        'Slot per Carte': 'Card Slots',
        'Tasca Interna con Cerniera': 'Internal Zipper Pocket',
        'Tasca Esterna': 'External Pocket',
        'Tasca Aperta': 'Slip Pocket',
        'Anello Penna': 'Pen Loop',
        'Multi-Scomparto': 'Multi-Compartment',
    },
    
    'fr': {
        # Categories
        'Materiali': 'Matériaux',
        'Visuale': 'Visuel',
        'Dimensioni': 'Dimensions',
        'Speciale': 'Spécial',
        'Sostenibilità': 'Durabilité',
        'Culturale': 'Culturel',
        'Accessori': 'Accessoires',
        'Categorie': 'Catégories',
        
        # Trait Types
        'Materiale Primario': 'Matériau Principal',
        'Finitura': 'Finition',
        'Tecnica': 'Technique',
        'Colore Primario': 'Couleur Principale',
        'Stile': 'Style',
        'Atmosfera': 'Ambiance',
        'Dimensione': 'Taille',
        'Peso': 'Poids',
        'Altezza': 'Hauteur',
        'Larghezza': 'Largeur',
        'Edizione': 'Édition',
        'Firma': 'Signature',
        'Condizione': 'Condition',
        'Anno di Creazione': 'Année de Création',
        'Contenuto Riciclato': 'Contenu Recyclé',
        'Impronta Carbonica': 'Empreinte Carbone',
        'Certificazione Eco': 'Certification Écologique',
        'Punteggio Sostenibilità': 'Score de Durabilité',
        'Origine Culturale': 'Origine Culturelle',
        'Focus Tematico': 'Focus Thématique',
        'Tecnica Artigianale': 'Technique Artisanale',
        'Tipo di Edizione': 'Type d\'Édition',
        
        # Accessory Types  
        'Tipo di Accessorio': 'Type d\'Accessoire',
        'Componente Accessorio': 'Composant d\'Accessoire',
        'Tipo di Chiusura': 'Type de Fermeture',
        'Finitura Hardware': 'Finition de Quincaillerie',
        'Tipo di Cinghia': 'Type de Sangle',
        'Layout Tasche': 'Disposition des Poches',
        'Categoria Dimensioni': 'Catégorie de Taille',
        'Texture': 'Texture',
        'Fodera': 'Doublure',
        'Occasione': 'Occasion',
        'Compatibilità': 'Compatibilité',
        'Protezione Acqua': 'Protection Contre l\'Eau',
        'Personalizzazione': 'Personnalisation',
        'Struttura': 'Structure',
        
        # Values - Categories
        'Giochi': 'Jeux',
        'Business': 'Affaires',
        'Arte': 'Art',
        'Musica': 'Musique',
        'Sport': 'Sports',
        'Educazione': 'Éducation',
        'Scienza': 'Science',
        'Tecnologia': 'Technologie',
        'Collezionabili': 'Objets de Collection',
        'Fantasy': 'Fantaisie',
        'Storia': 'Histoire',
        'Natura': 'Nature',
        'Moda': 'Mode',
        'Cibo': 'Nourriture',
        'Viaggi': 'Voyage',
        
        # Materials
        'Legno': 'Bois',
        'Metallo': 'Métal',
        'Tela': 'Toile',
        'Carta': 'Papier',
        'Ceramica': 'Céramique',
        'Vetro': 'Verre',
        'Pietra': 'Pierre',
        'Tessuto': 'Tissu',
        'Plastica': 'Plastique',
        'Tecnica Mista': 'Médias Mixtes',
        'Pelle': 'Cuir',
        'Argilla': 'Argile',
        'Marmo': 'Marbre',
        'Granito': 'Granit',
        'Cemento': 'Béton',
        'Gesso': 'Plâtre',
        'Resina': 'Résine',
        'Gomma': 'Caoutchouc',
        'Acrilico': 'Acrylique',
        'Inchiostro': 'Encre',
        'Pittura a Olio': 'Peinture à l\'Huile',
        'Acquerello': 'Aquarelle',
        'Carboncino': 'Fusain',
        'Pastello': 'Pastel',
        'Digitale': 'Numérique',
        'Fotografico': 'Photographique',
        'Organico': 'Organique',
        'Riciclato': 'Recyclé',
        'Composito': 'Composite',
        
        # Finish
        'Opaco': 'Mat',
        'Lucido': 'Brillant',
        'Satinato': 'Satiné',
        'Grezzo': 'Brut',
        'Lucidato': 'Poli',
        'Spazzolato': 'Brossé',
        'Patina': 'Patine',
        'Texturizzato': 'Texturé',
        
        # Primary Colors
        'Rosso': 'Rouge',
        'Blu': 'Bleu',
        'Verde': 'Vert',
        'Giallo': 'Jaune',
        'Arancione': 'Orange',
        'Viola': 'Violet',
        'Nero': 'Noir',
        'Bianco': 'Blanc',
        'Grigio': 'Gris',
        'Marrone': 'Marron',
        'Oro': 'Or',
        'Argento': 'Argent',
        
        # Style
        'Moderno': 'Moderne',
        'Classico': 'Classique',
        'Minimalista': 'Minimaliste',
        'Astratto': 'Abstrait',
        'Realistico': 'Réaliste',
        'Surreale': 'Surréel',
        'Pop Art': 'Pop Art',
        'Rinascimentale': 'Renaissance',
        'Contemporaneo': 'Contemporain',
        
        # Mood
        'Sereno': 'Serein',
        'Energico': 'Énergique',
        'Misterioso': 'Mystérieux',
        'Gioioso': 'Joyeux',
        'Melanconico': 'Mélancolique',
        'Drammatico': 'Dramatique',
        'Pacifico': 'Paisible',
        'Intenso': 'Intense',
        
        # Size
        'Extra Piccolo': 'Très Petit',
        'Piccolo': 'Petit',
        'Medio': 'Moyen',
        'Grande': 'Grand',
        'Extra Grande': 'Très Grand',
        
        # Edition
        '1/1': '1/1',
        'Edizione Limitata': 'Édition Limitée',
        'Edizione Aperta': 'Édition Ouverte',
        'Prova d\'Artista': 'Épreuve d\'Artiste',
        'Prima Edizione': 'Première Édition',
        
        # Signature
        'Firmato': 'Signé',
        'Non Firmato': 'Non Signé',
        'Firmato e Numerato': 'Signé et Numéroté',
        'Certificato di Autenticità': 'Certificat d\'Authenticité',
        
        # Condition
        'Perfetto': 'Parfait',
        'Eccellente': 'Excellent',
        'Buono': 'Bon',
        'Discreto': 'Correct',
        'Restaurato': 'Restauré',
        'Vintage': 'Vintage',
        'Nuovo': 'Neuf',
        
        # Carbon Footprint
        'Neutro in Carbonio': 'Neutre en Carbone',
        'Basso Impatto': 'Faible Impact',
        'Medio Impatto': 'Impact Moyen',
        'Compensato': 'Compensé',
        
        # Eco Certification
        'Certificato FSC': 'Certifié FSC',
        'Biologico': 'Biologique',
        'Commercio Equo': 'Commerce Équitable',
        'Biodegradabile': 'Biodégradable',
        'Nessuna': 'Aucune',
        
        # Accessory Type
        'Borsa': 'Sac',
        'Zaino': 'Sac à Dos',
        'Borsa Tote': 'Cabas',
        'Tracolla': 'Bandoulière',
        'Borsa a Spalla': 'Sac à Épaule',
        'Pochette': 'Pochette',
        'Portafoglio': 'Portefeuille',
        'Porta Carte': 'Porte-Cartes',
        'Portamonete': 'Porte-Monnaie',
        'Cintura': 'Ceinture',
        'Portachiavi': 'Porte-Clés',
        'Custodia Telefono': 'Étui Téléphone',
        'Custodia Laptop': 'Housse Ordinateur',
        'Cinturino Orologio': 'Bracelet de Montre',
        'Occhiali da Sole': 'Lunettes de Soleil',
        'Montatura Occhiali': 'Monture de Lunettes',
        'Cappello': 'Chapeau',
        'Sciarpa': 'Écharpe',
        'Guanti': 'Gants',
        'Ombrello': 'Parapluie',
        
        # Hardware
        'Fibbia': 'Boucle',
        'Cerniera': 'Fermeture Éclair',
        'Chiusura Magnetica': 'Fermoir Magnétique',
        'Fermaglio': 'Fermoir',
        'Chiusura a Torsione': 'Verrou à Torsion',
        'Lucchetto': 'Cadenas',
        'Gancio': 'Crochet',
        'Laccio': 'Lien',
        'Velcro': 'Velcro',
        'Bottone': 'Bouton',
        'Borchia': 'Clou',
        'Rivetto': 'Rivet',
        'Catena': 'Chaîne',
        
        # Structure and other
        'Morbido': 'Souple',
        'Semi-Strutturato': 'Semi-Structuré',
        'Strutturato': 'Structuré',
        'Imbottito': 'Rembourré',
        'Liscio': 'Lisse',
        'Goffrato': 'Grainé',
        'Saffiano': 'Saffiano',
        'Trapuntato': 'Matelassé',
        'Intrecciato': 'Tissé',
        'Impresso': 'Gaufré',
        'Effetto Coccodrillo': 'Embossé Croco',
        'Finitura Scamosciata': 'Finition Daim',
        'Matelassé': 'Matelassé',
        'Senza Fodera': 'Non Doublé',
        'Fodera in Cotone': 'Doublure Coton',
        'Fodera in Microfibra': 'Doublure Microfibre',
        'Fodera Scamosciata': 'Doublure Daim',
        'Fodera in Raso': 'Doublure Satin',
        'Quotidiano': 'Quotidien',
        'Viaggio': 'Voyage',
        'Sera': 'Soirée',
        'Formale': 'Formel',
        'Outdoor': 'Extérieur',
        'Telefono': 'Téléphone',
        'Tablet': 'Tablette',
        'Laptop 13"': 'Ordinateur 13"',
        'Laptop 14"': 'Ordinateur 14"',
        'Laptop 15"': 'Ordinateur 15"',
        'Laptop 16"': 'Ordinateur 16"',
        'Passaporto': 'Passeport',
        'Resistente agli Schizzi': 'Résistant aux Éclaboussures',
        'Resistente all\'Acqua': 'Résistant à l\'Eau',
        'Impermeabile': 'Étanche',
        'Monogramma': 'Monogramme',
        'Incisione': 'Gravure',
        'Patch Personalizzata': 'Patch Personnalisé',
        'Colore Personalizzato': 'Couleur Personnalisée',
        
        # Additional
        'Regolabile': 'Ajustable',
        'Rimovibile': 'Détachable',
        'Manico Superiore': 'Poignée Supérieure',
        'Spallacci Zaino': 'Sangles de Sac à Dos',
        'Cinturino da Polso': 'Bracelet',
        'Mini': 'Mini',
        'Oversize': 'Surdimensionné',
        'Coulisse': 'Cordon de Serrage',
        'Gancio e Occhiello': 'Crochet et Boucle',
        'Tasto a Leva': 'Bouton-Bascule',
        'Clip': 'Pince',
        'Aperto in Alto': 'Ouverture Libre',
        'Oro Rosa': 'Or Rose',
        'Nichel': 'Nickel',
        'Gunmetal': 'Métal Pistolet',
        'Ottone': 'Laiton',
        'Antico': 'Antique',
        'Slot per Carte': 'Fentes pour Cartes',
        'Tasca Interna con Cerniera': 'Poche Intérieure à Fermeture',
        'Tasca Esterna': 'Poche Extérieure',
        'Tasca Aperta': 'Poche Glissière',
        'Anello Penna': 'Boucle Stylo',
        'Multi-Scomparto': 'Multi-Compartiments',
    }
}

# Continuerò con le altre lingue nel prossimo file...
