<?php

/**
 * Dual Architecture EGI - UI Messages
 *
 * English translations for user interface messages related
 * to Auto-Mint and Pre-Mint EGI management.
 *
 * @package FlorenceEGI\Translations
 * @author Padmin D. Curtis (AI Partner OS3.0) for Fabio Cherici
 * @version 2.0.0 (FlorenceEGI - Dual Architecture + AI Traits Modal)
 * @date 2025-11-04
 */

return [
    /*
    |--------------------------------------------------------------------------
    | Auto-Mint Messages
    |--------------------------------------------------------------------------
    */
    'auto_mint_enabled' => 'Auto-Mint successfully enabled. You can now mint your EGI whenever you want.',
    'auto_mint_disabled' => 'Auto-Mint disabled. The EGI is now available for sale on the marketplace.',

    /*
    |--------------------------------------------------------------------------
    | AI Analysis Messages
    |--------------------------------------------------------------------------
    */
    'ai_analysis_requested' => 'AI analysis request successfully sent. N.A.T.A.N will process your data shortly.',
    'description_generated' => 'Description successfully generated by N.A.T.A.N AI and saved to your EGI.',
    'description_improved' => 'Description successfully improved by N.A.T.A.N AI and saved to your EGI.',

    /*
    |--------------------------------------------------------------------------
    | Promotion Messages
    |--------------------------------------------------------------------------
    */
    'promotion_initiated' => 'Blockchain promotion initiated. Transaction is being processed on Algorand network.',

    /*
    |--------------------------------------------------------------------------
    | EGI Type Labels
    |--------------------------------------------------------------------------
    */
    'type' => [
        'ASA' => 'Classic EGI',
        'SmartContract' => 'Living EGI',
        'PreMint' => 'Pre-Mint',
    ],

    /*
    |--------------------------------------------------------------------------
    | Status Messages
    |--------------------------------------------------------------------------
    */
    'status' => [
        'pre_mint_active' => 'Pre-Mint Active',
        'auto_mint_enabled' => 'Auto-Mint Enabled',
        'minting_in_progress' => 'Minting in Progress',
        'minted' => 'Minted',
    ],

    /*
    |--------------------------------------------------------------------------
    | AI Traits Generation Messages
    |--------------------------------------------------------------------------
    */
    'ai' => [
        'unauthorized' => 'You must be authenticated to use this feature.',
        'forbidden' => 'You do not have permission to access this resource.',
        'generation_started' => 'AI traits generation started successfully! N.A.T.A.N is analyzing the image.',
        'generation_failed' => 'An error occurred during traits generation. Please try again later.',
        'generation_not_found' => 'Generation session not found.',
        'review_completed' => 'Proposal review completed successfully.',
        'review_failed' => 'An error occurred during review. Please try again later.',
        'traits_applied' => 'Traits successfully applied to your EGI!',
        'apply_failed' => 'An error occurred while applying traits. Please try again later.',

        // UI Labels
        'generate_traits' => 'Generate Traits with AI',
        'requested_count' => 'Number of traits to generate',
        'trait_proposals' => 'Trait Proposals',
        'confidence' => 'Confidence',
        'match_type' => 'Match Type',
        'exact_match' => 'Exact Match',
        'fuzzy_match' => 'Fuzzy Match',
        'new_value' => 'New Value',
        'new_type' => 'New Type',
        'new_category' => 'New Category',
        'approve' => 'Approve',
        'reject' => 'Reject',
        'modify' => 'Modify',
        'apply_traits' => 'Apply Approved Traits',
        'analyzing' => 'N.A.T.A.N is analyzing...',
        'pending_review' => 'Pending Review',
        'approved' => 'Approved',
        'rejected' => 'Rejected',
        'applied' => 'Applied',
        
        // Modal UI Labels (v2.0)
        'review_proposals_modal' => 'Review AI Proposals',
        'proposals_modal_title' => 'AI Trait Proposals',
        'close_modal' => 'Close',
        'approve_all' => 'Approve All',
        'reject_all' => 'Reject All',
        'apply_selected' => 'Apply',
    ],
];


