<?php

return [
    // Page titles
    'page_title' => 'Account Statements',
    'page_subtitle' => 'View and download your statements for Egili, invoices and other documents',

    // Tabs
    'tabs' => [
        'egili' => 'Egili Statement',
        'eur' => 'EUR Statement',
        'invoices' => 'Invoices', // Future
        'receipts' => 'Receipts', // Future
    ],

    // Filters
    'filters' => [
        'title' => 'Period Filters',
        'today' => 'Today',
        'week' => 'Week',
        'month' => 'Month',
        'year' => 'Year',
        'custom' => 'Custom',
        'date_from' => 'From',
        'date_to' => 'To',
        'apply' => 'Apply Filters',
        'reset' => 'Reset',
    ],

    // EGILI Statement
    'egili' => [
        'title' => 'Egili Statement',
        'subtitle' => 'Your Egili wallet transactions',
        'period' => 'Period: :from - :to',
        'download_pdf' => 'Download PDF',
        'no_transactions' => 'No transactions in the selected period',
        
        // Summary
        'summary' => [
            'title' => 'Period Summary',
            'starting_balance' => 'Starting Balance',
            'total_income' => 'Total Income',
            'total_expenses' => 'Total Expenses',
            'ending_balance' => 'Ending Balance',
            'transaction_count' => 'Number of Transactions',
        ],
        
        // Table headers
        'table' => [
            'date' => 'Date',
            'time' => 'Time',
            'description' => 'Description',
            'type' => 'Type',
            'income' => 'Income',
            'expenses' => 'Expenses',
            'balance' => 'Balance',
        ],
        
        // Transaction types
        'types' => [
            'earned' => 'Earned',
            'spent' => 'Spent',
            'purchase' => 'Egili Purchase',
            'admin_grant' => 'Admin Grant',
            'admin_deduct' => 'Admin Deduct',
            'refund' => 'Refund',
            'expiration' => 'Expiration',
            'initial_bonus' => 'Initial Bonus',
            'gift' => 'Egili Gift',
            'ai_feature' => 'AI Feature',
            'collection_subscription' => 'Collection Subscription',
            'bonus' => 'Bonus',
            'other' => 'Other',
        ],
    ],

    // EUR Statement
    'eur' => [
        'title' => 'EUR Statement',
        'subtitle' => 'Expenses and income in EUR currency',
        'period' => 'Period: :from - :to',
        'download_pdf' => 'Download PDF',
        'no_transactions' => 'No transactions in the selected period',
        
        // Summary
        'summary' => [
            'title' => 'Period Summary',
            'total_expenses' => 'Total Expenses',
            'total_income' => 'Total Income',
            'net_balance' => 'Net Balance',
            'transaction_count' => 'Number of Transactions',
        ],
        
        // Table headers
        'table' => [
            'date' => 'Date',
            'time' => 'Time',
            'description' => 'Description',
            'merchant' => 'Merchant / PSP',
            'beneficiary' => 'Beneficiary',
            'expenses' => 'Expenses',
            'income' => 'Income',
            'reference' => 'Reference',
        ],
        
        // Transaction types
        'types' => [
            'egili_purchase' => 'Egili Purchase',
            'egi_mint' => 'EGI Mint',
            'egi_mint_split' => 'EGI Mint (Split Payment)',
            'egi_sale_distribution' => 'EGI Sale',
            'split_payment' => 'Split Payment',
        ],
    ],

    // PDF specific
    'pdf' => [
        'title' => 'EGILI ACCOUNT STATEMENT',
        'document_title' => 'Egili Wallet Statement',
        'generated_on' => 'Generated on',
        'account_holder' => 'Account Holder',
        'account_id' => 'Account ID',
        'wallet_id' => 'Wallet ID',
        'footer_disclaimer' => 'This document is automatically generated by FlorenceEGI system. For support: support@florenceegi.it',
        'page_number' => 'Page :current of :total',
    ],

    // Messages
    'messages' => [
        'filter_applied' => 'Filter applied successfully',
        'pdf_generated' => 'PDF generated successfully',
        'error_generating_pdf' => 'Error generating PDF',
    ],
];

