#!/bin/bash

# 📅 EGI Daily Code Counter - Simple Version
# Author: Padmin D. Curtis (AI Partner OS3.0)
# Version: 1.1.0 (FlorenceEGI - Simple Daily Tracker)
# Date: 2025-09-29
# Purpose: Conta le righe di codice scritte oggi (versione semplificata)

# Colori
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

# Parametri
DATE_FROM="${1:-$(date +%Y-%m-%d)}"
AUTHOR_FILTER="${2:-$(git config user.name)}"

echo -e "${BOLD}${BLUE}"
echo "═══════════════════════════════════════════════════════════════════"
echo "📅 FLORENCE EGI - PRODUTTIVITÀ GIORNALIERA"
echo "═══════════════════════════════════════════════════════════════════"
echo -e "${NC}"

echo -e "${CYAN}📅 Data: ${DATE_FROM}${NC}"
echo -e "${CYAN}👤 Autore: ${AUTHOR_FILTER}${NC}"
echo ""

if ! git rev-parse --git-dir > /dev/null 2>&1; then
    echo -e "${RED}❌ Non siamo in un repository Git!${NC}"
    exit 1
fi

# Statistiche semplici
commits_today=$(git log --since="${DATE_FROM} 00:00:00" --until="${DATE_FROM} 23:59:59" \
                   --author="${AUTHOR_FILTER}" --oneline | wc -l)

files_modified=$(git log --since="${DATE_FROM} 00:00:00" --until="${DATE_FROM} 23:59:59" \
                    --author="${AUTHOR_FILTER}" --name-only --pretty=format: \
                    | sort -u | wc -l)

# Calcolo righe totali
total_stats=$(git log --since="${DATE_FROM} 00:00:00" --until="${DATE_FROM} 23:59:59" \
                 --author="${AUTHOR_FILTER}" --numstat --pretty=format:"" \
                 | awk '{added+=$1; removed+=$2} END {print added+0, removed+0}')

read total_added total_removed <<< "$total_stats"
total_net=$((total_added - total_removed))

echo -e "${BOLD}${GREEN}📊 RISULTATI GIORNALIERI${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo -e "${GREEN}📝 Commit: ${BOLD}${commits_today}${NC}"
echo -e "${BLUE}📁 File modificati: ${BOLD}${files_modified}${NC}"
echo -e "${GREEN}➕ Righe aggiunte: ${BOLD}${total_added}${NC}"
echo -e "${YELLOW}➖ Righe rimosse: ${BOLD}${total_removed}${NC}"
echo -e "${BOLD}${CYAN}🚀 RIGHE NETTE: ${total_net}${NC}"

# Valutazione produttività
echo ""
if [ $total_net -gt 1000 ]; then
    echo -e "${BOLD}${GREEN}💪 PRODUTTIVITÀ: ULTRA ECCELLENZA! 🔥${NC}"
elif [ $total_net -gt 500 ]; then
    echo -e "${BOLD}${YELLOW}⚡ PRODUTTIVITÀ: ECCELLENTE! ⭐${NC}"
elif [ $total_net -gt 200 ]; then
    echo -e "${BOLD}${BLUE}👍 PRODUTTIVITÀ: BUONA! 👌${NC}"
elif [ $total_net -gt 0 ]; then
    echo -e "${BOLD}${CYAN}📝 PRODUTTIVITÀ: STANDARD${NC}"
else
    echo -e "${BOLD}${YELLOW}🧹 GIORNATA DI REFACTORING${NC}"
fi

# Top file modificati oggi
echo ""
echo -e "${BOLD}${BLUE}📁 FILE PIÙ MODIFICATI OGGI:${NC}"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

git log --since="${DATE_FROM} 00:00:00" --until="${DATE_FROM} 23:59:59" \
       --author="${AUTHOR_FILTER}" --name-only --pretty=format: \
       | sort | uniq -c | sort -nr | head -5 | \
       while read count file; do
           if [ ! -z "$file" ]; then
               echo -e "${GREEN}${count}x${NC} ${file}"
           fi
       done

# Commit di oggi
if [ $commits_today -gt 0 ]; then
    echo ""
    echo -e "${BOLD}${BLUE}📝 COMMIT DI OGGI:${NC}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    git log --since="${DATE_FROM} 00:00:00" --until="${DATE_FROM} 23:59:59" \
           --author="${AUTHOR_FILTER}" --oneline --decorate
fi

echo ""
echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
echo -e "${BOLD}Generated by: Padmin D. Curtis OS3.0 | $(date '+%Y-%m-%d %H:%M:%S')${NC}"
echo -e "${BOLD}${BLUE}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"